name: "reservation"

networks:
  default:
    name: "reservation"

volumes:
  reservation-pg:

services:
  postgres:
    container_name: "reservation-pg"
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "reservation"
    volumes:
      - reservation-pg:/var/lib/postgresql/data
  backend:
    build:
      context: .
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
